# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'questionnaire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for questionnaire

  pod 'DropDown'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

  target 'questionnaireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'questionnaireUITests' do
    # Pods for testing
  end

end
